# Generated by Django 3.2.12 on 2023-10-14 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_p9', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='description',
            field=models.TextField(default='', max_length=1000),
        ),
    ]
